travis:
  secure:
    BINSTAR_TOKEN: mBd4y7z+n02X06GAQv3GiLeOPbhiK/1oDHj7Hr4BBRW7UMkwrOYaq9kDiBafyqSuQWop22vUI6qCC4yO4UNF1CKL/z1paDQNXSQVOUQorWwhJrEv5HVyQMIcZwSZtr9TmmAIBX5hfI7CtdU++DeDNCd4xarJLX/DkHuHXV2iVpCLUOCjTv/vQVghwyY8UZH0WTsnadzQO873/aTYr2Rd/UeO5atIcMHtFkR/4B3+Ptc57y6QYyio5Q78/OTZWwgB80GUUPjbTE7DWXmgVxgi2oKzaw69kSI3FJa7kXwAxDoIrE1FbuMQSSpIf7VUBg3D1c+qZNdiVzGbYbFjin2pPe6XNjPkpQ+o7qe7WI10o5DDUoiAiiVmS4IBh4i64pFkQQ1QvdBAdV4p64QLs4OhZO6/quYeZYDXtW0O2arbvefbZdur/GHGVWeIYdaPmmAs1p3/apyOzPQF5O9qIqiOVTR32LnD0D3vdXWbjtAPJA7fYUL+rM4MNSmDCNnMRcIH/0z5iPrz871VMpjlRdgdY2WtSYqQlWDNT8LHXwmqCF/6E+SI/hkyPCWi59iZFJODJPKUTf9ruDa+92FW5QX38fj/9FC5Vz1VKHo3FOZjyauE1I5QO+eKkubRmQeVIz6d5dJWzOqDNv1SQ5fZhcHf1F8f+COB4472rQP50kRQ7rY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
