travis:
  secure:
    BINSTAR_TOKEN: OQF4q4CjpSWpk2wiDyb93MNB0tAHSJwpE888MnOo7MW2BKDRLHoyeHFqjUKyNpjlRrN0fL6Qlb99d6M5+Qw3dEYuOpm6EFf+QGPLpVyZUZ0LTlunBcpD7eenLzk4bW+ZXtM9uJxxw0DHzSg3bbPQ2RjUdXAY2FkD9sVzAeqhBvBEavhASTom0q8J4RvR+rmVjXyfN563oWclb4gRTefs1cDDZ7k0eI045imKm1gExnKVFKAcTnKnTK0RbY/Y0cM0noSpaa/FfrClXTktgg2tlsAfgUNpy/CwEq0QQWRYURBNkeDfVX3Y//RH+4HWhtajqRupEJCrZ7C45YBDDLCLY/cMlCCnxq3AT8XoJjNwWyUv9miRxs5RD4aSUCo2/icvdvwhBWW2mpoUjxi0qEbeKla/9xQ0kPyaz19uDtG+4AfLNPGqGfBdo/bmxm9q8hIKetsG2eDUhv6D/2w5i4b7xtQpzHS2EvRb8+LelcOmKVOUEEjVm0LtZufK03eG6uYLh2M7zCefVX/xHAqkLNnGNba37IXjtSfNkvgKi9hArqOaBVMBc192ScTJFYRxXVR5c4/YwFq8NJMba1bNZkHcigv0zc0s9Ur46zGtBZ3AwMnmBQVBnEACxCfvpCas7o8qsfIpf1vTPbAKOzCEy/oVm7gaF6Ol2pSocgOJI8Q9P0s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
